import "dotenv/config";
import { getAppSetting } from "../db";

async function test() {
  const session = await getAppSetting("autodata_tokens");
  
  if (!session || !session.awswaf) {
    console.log("No tokens found!");
    process.exit(1);
  }

  const tokens = session;
  const awswaf = tokens.awswaf;
  
  // Extract HttpOnly session cookie from the rawCookies field generated by background.js
  let ssess = "";
  if (tokens.rawCookies) {
      const match = tokens.rawCookies.match(/SSESS[a-zA-Z0-9]+=[^;]+/);
      if (match) ssess = match[0];
  }

  const headers = {
    "Cookie": `awswaf_session_storage=${awswaf}; ${ssess}`,
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
    "Accept": "application/json",
    "Origin": "https://workshop.autodata-group.com",
    "Referer": "https://workshop.autodata-group.com/"
  };

  const apiUrls = [
      "https://workshop.autodata-group.com/w1/service-schedules-intervals/OPL16080/OPLSG0000597"
  ];

  for (const api of apiUrls) {
     const ar = await fetch(api, { headers });
     const text = await ar.text();
     console.log(`\nTesting possible API ${api}`);
     console.log("Status: ", ar.status);
     console.log(text.substring(0, 500));
  }

  process.exit(0);
}
test();
